catalog_remote_url = "http://192.168.1.70:5002/asv4/v4/catalog.yaml"
git_path = "runafe.cn:8088/lamp/lamp-ui/unified/system.git"
pre_build_commit = "43f5bd14733afbed2b0c3b8d46a39b83573ac355"
diff_ignore = [
  "**/env.d.ts",
  "**/__tests__/*",
  "**/package.json",
  "**/*.toml"
]
registries = [ "http://192.168.1.70:8081/repository/runafe-hosted/" ]

[meta.node-demo]
order = 5

[meta.pkg-demo]
order = 10
